default:
  image: ruby:2.6.0

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: bike_tipo_vc_test
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASS
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - Test
  - Production

Enviromnent_Test:
  stage: Test
  environment: test
  only:
    - tags
    - branches
  when: manual
  allow_failure: true
  script:
    - bundle install
    - bundle exec rails db:migrate RAILS_ENV=test
    - bundle exec rspec
Enviromnent_Production:
  stage: Production
  environment: production
  when: manual
  only:
    - tags
  allow_failure: true
  script:
    - dpl --provider=heroku --app=springfield-bike-tipo-vc --api-key=$HEROKU_PRODUCTION_API_KEY