# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.6.3

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - pipe: atlassian/heroku-deploy:1.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              WAIT: 'true' # wait for build completion and exit the pipescript:                                           
          - bundle install

definitions:
  caches:
    bundler: ./vendor
    