version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: biker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 15432:5432
    volumes:
      - ../dump_postgres:/var/www/html/bike_tipo_vc/dump
    networks:
      - database-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: biker@bike_tipo_vc.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - database-network
  portainer:
    image: portainer/portainer
    container_name: portainer
    environment:
      - VIRTUAL_HOST=dev.portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../portainer_data/:/var/www/html/bike_tipo_vc/portainer_data
    ports:
      - 9000:9000
    restart: always
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - database-network

  application:
    tty: true
    stdin_open: true
    build: ./
    container_name: bike_tipo_vc
    env_file:
      - .env
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    privileged: true
    volumes:
      - ../:/var/www/html/bike_tipo_vc
    ports:
      - 3000:3000
      - 80:80
    depends_on:
      - postgres
      - redis
    networks:
      - database-network

networks:
  database-network:
    driver: bridge