common: &common
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf-8
  username: <%= Rails.application.config.app.postgres.user %>
  password: <%= Rails.application.config.app.postgres.password %>

development:
  <<: *common
  host: postgres_db
  database: bike_tipo_vc_development

test:
  <<: *common
  host: <%= ENV['POSTGRES_HOST'] %>
  database: bike_tipo_vc_test

production:
  <<: *common
  database: <%= Rails.application.config.app.postgres.database %>
  host: <%= Rails.application.config.app.postgres.host %>
